import type { Metadata } from "next";
import Header from "./components/header/Header";
import "./globals.css";
import StoreProvider from "./StoreProvider";

export const metadata: Metadata = {
  title: "java rush next site",
  description: "Generated by create next app sfgsd a fg dd",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) { 

  return (
    <html lang="en">
      <body>
        <StoreProvider>
           <Header/>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
